import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
	container: {
		flexGrow: 1,
		backgroundColor: "white",
		paddingVertical: 20,
		paddingHorizontal: 15,
	},
	loadingContainer: {
		backgroundColor: "white",
		justifyContent: "center",
		alignItems: "center",
	},
	categoryContainer: {
		marginBottom: 20,
		alignItems: "center",
	},
	categoryTitle: {
		fontSize: 26,
		fontWeight: "bold",
		marginBottom: 10,
		color: "#FFA500",
		textAlign: "center",
	},
	subCategoryContainer: {
		marginBottom: 15,
	},
	subCategoryTitle: {
		fontSize: 20,
		fontWeight: "bold",
		marginBottom: 10,
		color: "#FFA500",
	},
	subItem: {
		width: 350,
		paddingVertical: 20,
		paddingHorizontal: 15,
		borderRadius: 8,
		backgroundColor: "white",
		marginBottom: 10,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.2,
		elevation: 3,
	},
	subItemTitle: {
		fontSize: 18,
		fontWeight: "bold",
		marginBottom: 5,
		color: "#000",
		marginLeft: 10,
	},
	subItemText: {
		fontSize: 16,
		lineHeight: 24,
		color: "#333",
	},
	iconContainer: {
		position: "absolute",
		alignItems: "center",
		justifyContent: "center",
		width: 50,
		height: 50,
		borderRadius: 25,
		backgroundColor: "transparent",
		top: 35,
		left: 36,
	},
	title: {
		fontSize: 26,
		fontWeight: "bold",
		color: "orange",
	},
	button: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		padding: 10,
		borderWidth: 2,
		borderColor: "orange",
		borderRadius: 25,
		marginBottom: 20,
	},
	upScrollButton: {
		position: "absolute",
		top: "78%",
		right: "5.5%",
		backgroundColor: "orange",
		borderRadius: 25,
		width: 60,
		height: 60,
		alignItems: "center",
		justifyContent: "center",
		elevation: 5,
		borderRadius: 30,
		elevation: 6,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.3,
		shadowRadius: 3,
		zIndex: 999,
	},
});

export default styles;
